export const employeeFormContainer = [
    {
        formFields: [
            {
                label: 'Employee Name',
                name: 'employeeName',
                inputType: 'text',
                placeholder: 'Enter Employee Name',
                classStyle: 'col-6',
                required: true,
            },
            {
                label: 'Mobile No',
                name: 'mobileNo',
                inputType: 'text',
                placeholder: 'Enter Mobile Number',
                classStyle: 'col-6',
                required: true,
            },
            {
                label: 'Role',
                name: 'roleId',
                inputType: 'select',
                classStyle: 'col-6',
                required: true,
                optionList: 'rolesList',
                displayKey: 'roleName',
                uniqueKey: 'roleId',
            },
            {
                label: 'Department',
                name: 'departmentId',
                inputType: 'select',
                classStyle: 'col-6',
                required: true,
                optionList: 'departmentsList',
                displayKey: 'department_name',
                uniqueKey: 'department_id',
            },
            {
                label: 'Address I',
                name: 'addressI',
                inputType: 'textarea',
                placeholder: 'Enter Address I',
                classStyle: 'col-6',
                rows: 2,
            },
            {
                label: 'Address II',
                name: 'addressII',
                inputType: 'textarea',
                placeholder: 'Enter Address II',
                classStyle: 'col-6',
                rows: 2,
            },
            {
                label: 'Pincode',
                name: 'pincode',
                inputType: 'text',
                placeholder: 'Enter Pincode',
                classStyle: 'col-6',
            },
            {
                label: 'Enable Authentication',
                name: 'isAuthenticated',
                inputType: 'checkbox',
                classStyle: 'col-12',
                onChange: 'handleAuthenticationChange',
            },
        ],
    },
];
